/**
 * Backrooms游戏模组 - 文档内容
 */

import type { GameModDocs } from '../types.js';
import { BACKROOMS_VARIABLE_COUNT } from './variables.js';

export function getBackroomsDocs(): GameModDocs {
  return {
    name: '后室',
    description: `轻量级后室游戏模组（${BACKROOMS_VARIABLE_COUNT}个示例变量 + 4个通用函数）`,
    variables: [],
    functions: [],
    usage: {
      setup: [
        '一、变量定义',
        '',
        '核心属性（3个）',
        '',
        '1. sanity - 理智值',
        'number | 范围0-100 | 初始100',
        '精神健康值，归零会精神崩溃',
        '',
        '2. health - 生命值',
        'number | 范围0-100 | 初始100',
        '物理生命值，归零会死亡',
        '',
        '3. stamina - 体力值',
        'number | 范围0-100 | 初始100',
        '体力值，影响逃跑和行动能力',
        '',
        '',
        '常用物品（6个）',
        '',
        '4. almond_water - 杏仁水',
        'number | 范围0+ | 初始3',
        '后室最重要资源，恢复理智',
        '',
        '5. supplies - 物资包',
        'number | 范围0+ | 初始2',
        '综合物资，恢复生命和体力',
        '',
        '6. bandages - 绷带',
        'number | 范围0+ | 初始3',
        '医疗用品，恢复生命',
        '',
        '7. food - 食物',
        'number | 范围0+ | 初始5',
        '食物，恢复体力',
        '',
        '8. water - 水',
        'number | 范围0+ | 初始3',
        '饮用水，基础需求',
        '',
        '9. flashlight_battery - 手电筒电量',
        'number | 范围0-100 | 初始100',
        '手电筒电量，用于照明',
        '',
        '',
        '游戏进度（1个）',
        '',
        '10. current_level - 当前Level',
        'string | 初始"level_0"',
        '记录当前所在的后室层级',
        '',
        '',
        '二、文本显示（集中）',
        '',
        '属性显示:',
        '理智：{{sanity}}/100',
        '生命：{{health}}/100',
        '体力：{{stamina}}/100',
        '',
        '物品显示:',
        '杏仁水 x{{almond_water}}',
        '物资包 x{{supplies}}',
        '绷带 x{{bandages}}',
        '',
        '条件显示:',
        '{{sanity < 30 ? "你快要疯了..." : ""}}',
        '{{health < 20 ? "你快要死了..." : ""}}',
        '{{almond_water > 0 ? "还有杏仁水" : "杏仁水用完了"}}',
        '',
        '状态判断:',
        '{{sanity < 30 ? "精神不稳" : sanity < 70 ? "有些紧张" : "平静"}}',
        '{{health < 30 ? "虚弱" : health < 70 ? "疲惫" : "良好"}}',
        '',
        '',
        '三、Blockly积木块',
        '',
        '1. 修改属性积木',
        '[修改属性 理智/生命/体力 增加/减少 数值]',
        '修改玩家属性，自动限制0-100',
        '对应函数: fns.modifyAttribute(\'sanity\', 20)',
        '',
        '2. 修改物品积木',
        '[修改物品 物品名 增加/减少 数量]',
        '修改物品数量，自动限制最小为0',
        '对应函数: fns.modifyItem(\'almond_water\', -1)',
        '',
        '3. 检查属性积木',
        '[属性 理智/生命/体力]',
        '获取当前属性值',
        '对应函数: fns.checkAttribute(\'sanity\')',
        '',
        '4. 检查物品积木',
        '[物品 物品名]',
        '获取当前物品数量',
        '对应函数: fns.checkItem(\'almond_water\')',
        '',
        '',
        '四、使用示例',
        '',
        '场景：使用杏仁水',
        '',
        '节点文本:',
        '"你有{{almond_water}}瓶杏仁水"',
        '',
        '选项："使用杏仁水"',
        '条件（Blockly）:',
        'if [物品 "almond_water"] > 0',
        '',
        '选中时（Blockly）:',
        '[修改物品 "almond_water" 减少 1]',
        '[修改属性 理智 增加 20]',
        '[修改属性 生命 增加 5]',
        '显示文本："你喝下杏仁水，感觉好多了"',
        '',
        '结果:',
        '杏仁水-1，理智+20，生命+5',
        '',
        '',
        '五、提示',
        '',
        `点击"注入变量（${BACKROOMS_VARIABLE_COUNT}个）"可自动创建示例变量`,
        '可自行添加更多变量，用法完全相同',
        '使用4个积木块即可实现所有生存游戏机制'
      ]
    }
  };
}
