/**
 * 生存游戏模组 - 使用文档
 */

import type { GameModDocs } from '../types.js';
import { SURVIVAL_VARIABLE_COUNT } from './variables.js';

export function getSurvivalDocs(): GameModDocs {
  return {
    name: '生存游戏',
    description: `提供基础生存属性管理（${SURVIVAL_VARIABLE_COUNT}个变量 + 2个函数）`,
    variables: [],
    functions: [],
    usage: {
      setup: [
        '一、变量定义',
        '',
        '1. health - 生命值',
        'number | 范围0-100 | 初始100',
        '当前生命值，降至0表示死亡',
        '',
        '2. hunger - 饥饿度',
        'number | 范围0-100 | 初始100',
        '当前饥饿度，降至0会持续掉血',
        '',
        '3. thirst - 口渴度',
        'number | 范围0-100 | 初始100',
        '当前口渴度，降至0会快速掉血',
        '',
        '',
        '二、文本显示（集中）',
        '',
        '直接显示:',
        '{{health}} HP',
        '饥饿度：{{hunger}}',
        '口渴度：{{thirst}}',
        '',
        '条件显示:',
        '{{health < 30 ? "濒死" : health < 60 ? "受伤" : "健康"}}',
        '{{hunger < 20 ? "饥饿难耐" : hunger < 50 ? "有点饿" : "饱腹"}}',
        '{{thirst < 20 ? "口干舌燥" : thirst < 50 ? "有点渴" : "水分充足"}}',
        '',
        '',
        '三、Blockly积木块',
        '',
        '1. 修改属性积木',
        '[生命值 增加 10]',
        '[饥饿度 减少 20]',
        '修改指定属性，自动限制在0-100范围',
        '对应函数: fns.modifyStat("health", 10)',
        '',
        '2. 获取属性积木',
        '[获取 生命值]',
        '返回当前属性值（0-100）',
        '对应函数: fns.getStat("health")',
        '',
        '',
        '四、使用示例',
        '',
        '场景1：吃食物恢复',
        '',
        '节点文本:',
        '"你吃了一块面包。"',
        '',
        '节点进入时（Blockly）:',
        '[饥饿度 增加 30]',
        '[生命值 增加 5]',
        '',
        '显示状态:',
        '"当前状态：{{health < 60 ? "受伤" : "健康"}}"',
        '',
        '场景2：条件检查',
        '',
        '选项条件（Blockly）:',
        '[获取 生命值] >= 50',
        '',
        '选项文本:',
        '"继续探索（需要50+生命值）"',
        '',
        '',
        '五、提示',
        '',
        `点击"注入变量（${SURVIVAL_VARIABLE_COUNT}个）"可自动创建：health、hunger、thirst`,
        '使用2个积木块即可实现所有生存属性操作',
        '属性变化数值由游戏作者根据剧情自定义'
      ]
    }
  };
}

