/**
 * 时间系统游戏模组 - 文档内容
 */

import type { GameModDocs } from '../types.js';
import { TIME_SYSTEM_VARIABLE_COUNT } from './variables.js';

export function getTimeSystemDocs(): GameModDocs {
  return {
    name: '时间',
    description: `提供游戏内时间流逝功能，自动处理进位规则（${TIME_SYSTEM_VARIABLE_COUNT}个变量）`,
    variables: [],
    functions: [],
    usage: {
      setup: [
        '一、时间变量（4个）',
        '',
        'minute 分钟',
        'number 0-59 初始0',
        '当前分钟数，60分钟进位到小时',
        '文本: {{minute}}分',
        '补零: 使用fns.formatTime()自动补零显示',
        'Blockly读取: vars[\'minute\']',
        'Blockly修改: 使用fns.addTime(分钟数)，自动处理进位',
        '进位: ≥60时自动hour+1，minute清零',
        '',
        'hour 小时',
        'number 0-23 初始0',
        '当前小时数，24小时进位到天',
        '文本: {{hour}}点',
        '时段: {{hour < 6 ? "凌晨" : hour < 12 ? "上午" : hour < 18 ? "下午" : "晚上"}}',
        'Blockly读取: vars[\'hour\']',
        'Blockly修改: 使用fns.addTime()自动累加',
        '进位: ≥24时自动day+1，hour清零',
        '',
        'day 天',
        'number 1-30 初始1',
        '当前日期，30天进位到月',
        '文本: 第{{day}}天',
        '日期: 第{{month}}月{{day}}日',
        'Blockly读取: vars[\'day\']',
        'Blockly修改: 使用fns.addTime()自动累加',
        '进位: >30时自动month+1，day重置为1',
        '注意: 从1开始计数',
        '',
        'month 月',
        'number 1-999+ 初始1',
        '当前月份，无上限持续累加',
        '文本: 第{{month}}月',
        '季节: {{month % 12 < 3 ? "春" : month % 12 < 6 ? "夏" : month % 12 < 9 ? "秋" : "冬"}}',
        'Blockly读取: vars[\'month\']',
        'Blockly修改: 使用fns.addTime()或手动设置',
        '进位: 无上限',
        '',
        '',
        '二、时间函数',
        '',
        'fns.addTime(分钟数)',
        '增加游戏时间，自动处理进位',
        '参数: number 分钟数',
        '示例: fns.addTime(30)',
        'Blockly: 使用"时间流逝"积木块',
        '',
        'fns.formatTime()',
        '获取格式化时间字符串',
        '参数: 无',
        '返回: "第1月 第1天 08:30"',
        '示例: 当前{{formatTime()}}',
        'Blockly: 使用"当前时间"积木块',
        '',
        '',
        '三、显示方法',
        '',
        '完整时间:',
        '{{formatTime()}}',
        '输出: 第1月 第1天 08:30',
        '',
        '单独显示:',
        '月: 第{{month}}月',
        '日: 第{{day}}天',
        '时: {{hour}}点',
        '分: {{minute}}分',
        '',
        '时段判断:',
        '{{hour < 6 ? "凌晨" : hour < 12 ? "上午" : hour < 18 ? "下午" : "晚上"}}',
        '{{hour >= 22 || hour < 6 ? "深夜" : "白天"}}',
        '',
        '',
        '四、常用时间参考',
        '',
        '5分钟 简短对话',
        '10分钟 喝水休息',
        '30分钟 吃饭',
        '60分钟 1小时活动',
        '120分钟 看电影',
        '480分钟 睡眠8小时',
        '1440分钟 完整一天',
        '',
        '',
        '五、使用示例',
        '',
        '基础流逝:',
        'fns.addTime(30);',
        '现在{{formatTime()}}',
        '',
        '长时间:',
        'fns.addTime(480); // 8小时',
        '',
        '时段判断:',
        '{{hour >= 18 ? "天色已晚" : "阳光明媚"}}',
        '',
        '倒计时:',
        'vars[\'deadline\'] = 5;',
        '{{day >= deadline ? "时间到" : ""}}',
        '',
        '',
        '提示:',
        `点击上方"注入变量（${TIME_SYSTEM_VARIABLE_COUNT}个）"按钮可自动创建本模组所需的4个时间变量`,
        '变量ID、类型、默认值已预定义（minute=0, hour=0, day=1, month=1）',
        '点击注入即可使用，时间流逝的具体数值由游戏作者根据剧情需要自定义'
      ]
    }
  };
}

