/**
 * 时间系统游戏模组 - 文档内容
 */

import type { GameModDocs } from '../types.js';
import { TIME_SYSTEM_VARIABLE_COUNT } from './variables.js';

export function getTimeSystemDocs(): GameModDocs {
  return {
    name: '时间',
    description: `提供游戏内时间流逝功能，自动处理进位规则（${TIME_SYSTEM_VARIABLE_COUNT}个变量 + 2个函数）`,
    variables: [],
    functions: [],
    usage: {
      setup: [
        '一、变量定义',
        '',
        '1. minute - 分钟',
        'number | 范围0-59 | 初始0',
        '当前分钟数，60分钟自动进位到小时',
        '',
        '2. hour - 小时',
        'number | 范围0-23 | 初始0',
        '当前小时数，24小时自动进位到天',
        '',
        '3. day - 天',
        'number | 范围1-30 | 初始1',
        '当前日期，30天自动进位到月',
        '',
        '4. month - 月',
        'number | 范围1+ | 初始1',
        '当前月份，无上限持续累加',
        '',
        '',
        '二、文本显示（集中）',
        '',
        '完整时间:',
        '{{fns.formatTime()}}',
        '输出: 第1月 第1天 08:30',
        '',
        '单独显示:',
        '{{minute}}分钟',
        '{{hour}}点',
        '第{{day}}天',
        '第{{month}}月',
        '',
        '条件显示:',
        '{{hour < 6 ? "凌晨" : hour < 12 ? "上午" : hour < 18 ? "下午" : "晚上"}}',
        '{{day >= 15 ? "已过半月" : "月初"}}',
        '',
        '',
        '三、Blockly积木块',
        '',
        '1. 时间流逝积木',
        '[时间流逝 30 分钟]',
        '增加30分钟，自动处理进位',
        '对应函数: fns.addTime(30)',
        '',
        '2. 当前时间积木',
        '[当前时间]',
        '返回格式化时间字符串',
        '对应函数: fns.formatTime()',
        '',
        '',
        '四、使用示例',
        '',
        '场景：对话消耗时间',
        '',
        '节点文本:',
        '"你们聊了一会儿天。"',
        '',
        '节点进入时（Blockly）:',
        '[时间流逝 10 分钟]',
        '',
        '显示当前时间:',
        '"现在是{{fns.formatTime()}}"',
        '',
        '',
        '五、提示',
        '',
        `点击"注入变量（${TIME_SYSTEM_VARIABLE_COUNT}个）"可自动创建：minute、hour、day、month`,
        '使用2个积木块即可实现所有时间相关功能',
        '时间流逝的具体数值由游戏作者自定义'
      ]
    }
  };
}
